#!/bin/bash
set -eu

PREFIX=
BASE_INSTALLDIR=${PREFIX}/usr/share
BINDIR=${PREFIX}/usr/bin
SHAREDOCDIR=${PREFIX}/usr/share/doc
SHAREAPPDIR=${PREFIX}/usr/share/applications
LIBDIR=${PREFIX}/usr/lib
ETCDIR=${PREFIX}/etc
KSRCDIR=/usr/src/ipfire-wall/kernel

ok()
{
	echo -e  "\t\e[1;32mOk\e[0m"
}

fail() 
{
	echo -e  "\n\e[1;31mFailed \e[1;31m:(\e[0m"
	exit 1
}

failed_unload()
{
  echo -e  "\n\e[1;31mFailed unloading ipfire-wall kernel module\e[0m"
  echo -e  "\e[1;33m* \e[0mClose any running iqfire (or ipfire) user interface and execute"
  echo -e  "\e[1;33m* \e[0mthis command again."
  echo -e  "\e[1;33m* \e[0mIf ipfire-wall was never installed, then ignore this message"
  echo -e "\n"
}



remove_rc_links()
{

	if [ -x ${ETCDIR}/init.d/rc.ipfire ]; then
		echo -e "${ETCDIR}/init.d/rc.ipfire"
		rm ${ETCDIR}/init.d/rc.ipfire	
	fi
			
	if [ -x ${ETCDIR}/rc0.d/K30ipfire ]; then
		echo -e "link ${ETCDIR}/rc0.d/K30ipfire"
		rm ${ETCDIR}/rc0.d/K30ipfire
	fi
			
	if [ -x ${ETCDIR}/rc6.d/K30ipfire ]; then
		echo -e "link ${ETCDIR}/rc6.d/K30ipfire"
		rm ${ETCDIR}/rc6.d/K30ipfire
	fi
			
	if [ -x ${ETCDIR}/rc2.d/S80ipfire ]; then
		echo -e "link ${ETCDIR}/rc2.d/S80ipfire"
		rm /${PREFIX}etc/rc2.d/S80ipfire
	fi
			
	if [ -x ${ETCDIR}/rc3.d/S80ipfire ]; then
		echo -e "link ${ETCDIR}/rc3.d/S80ipfire"
		rm ${ETCDIR}/rc3.d/S80ipfire
	fi	
			
	if [ -x ${ETCDIR}/rc.d/rc.ipfire ]; then
		echo -e "rc.ipfire -> directory \e[1;33m${PREFIX}rc.d\e[0m\n"
		rm ${ETCDIR}/rc.d/rc.ipfire	
	fi	

}


if [ "$1" = remove ] || [ "$1" = upgrade ]; then

echo -e -n "\e[1;32m* \e[0mUnloading kernel module ipfi if present..."

(modprobe -r ipfi && ok) || failed_unload

(echo -e -n "\e[1;32m* \e[0mremoving rc links...\t" && remove_rc_links && ok) || fail


if [ -d ${SHAREDOCDIR}/ipfire ]; then
	(echo -e -n "\e[1;32m* \e[0mremoving ipfire doc links...\t" && rm -rf ${SHAREDOCDIR}/ipfire && ok)|| fail
fi

if [ -d ${SHAREDOCDIR}/iqfire ]; then
	(echo -e -n "\e[1;32m* \e[0mremoving iqfire doc links...\t" && rm -rf ${SHAREDOCDIR}/iqfire && ok)|| fail
fi

if [ -x ${SHAREAPPDIR}/iqfire-root-kde.desktop ]; then
	(echo -e -n "\e[1;32m* \e[0mremoving ${SHAREAPPDIR}/iqfire-root-kde.desktop...\t" && rm -f ${SHAREAPPDIR}/iqfire-root-kde.desktop && ok)|| fail
fi

if [ -x ${SHAREAPPDIR}/iqfire-root-gnome.desktop ]; then
	(echo -e -n "\e[1;32m* \e[0mremoving ${SHAREAPPDIR}/iqfire-root-gnome.desktop...\t" && rm -f ${SHAREAPPDIR}/iqfire-root-gnome.desktop && ok)|| fail
fi

# remove directories which might be modified: dpkg would refuse to remove them
echo -e  -n "\e[1;32m*\e[0m removing \""$KSRCDIR"\" files"
(rm $KSRCDIR/* -rf && ok ) || fail
echo -e  -n "\e[1;32m*\e[0m removing \""$BASE_INSTALLDIR"/ipfire/*\" files"
(rm $BASE_INSTALLDIR/ipfire/* -rf && ok) || fail
echo -e  -n "\e[1;32m*\e[0m removing \""$BASE_INSTALLDIR"/iqfire/*\" files"
(rm $BASE_INSTALLDIR/iqfire/* -rf && ok ) || fail


echo -e  "\e[1;32m*\e[0m Successfully removed ipfirewall and all its components."
echo ""
echo -e  "\e[1;35;4mINFO\e[0m Manually remove the users' home configuration directories"
echo -e  "  (called \".IPFIRE\") or any icons you might have created."

fi

