#include "ignored_packets_set.h"
#include <QDir>
#include <QFile>
#include <QtDebug>
#include <macros.h>

IgnoredPacketsSet* IgnoredPacketsSet::_instance = NULL;

IgnoredPacketsSet* IgnoredPacketsSet::instance()
{
	if(_instance == NULL)
		return (_instance = new IgnoredPacketsSet() );
	else
		return _instance;
}

IgnoredPacketsSet::IgnoredPacketsSet()
{
	int ret = loadIgnoredPackets();
	if(ret < 0)
		loading_failed = true;
	else
		loading_failed = false;
}

IgnoredPacketsSet::~IgnoredPacketsSet()
{
	printf("delete ignoredPacketSet\n");
}

int IgnoredPacketsSet::loadIgnoredPackets()
{
	QString filename = QDir::homePath() + QString("/.IPFIRE/ignored");
	QFile ignfile(filename);
	QString line;
	
	plist.clear();
	
	if (!ignfile.open(QIODevice::ReadOnly | QIODevice::Text))
	{
		return -1;
	}
	else
	{
		while (!ignfile.atEnd()) 
		{
			line = ignfile.readLine();
			if(!line.startsWith("#"))
			{
				line = line.remove("\n");
				IgnoredPacket ipack(line);
				if(ipack.isValid())
				{
					plist.push_back(ipack);
				}
			}
			/* else it is a comment */
		}
	}
	ignfile.close();
	return plist.size();
}

int IgnoredPacketsSet::saveIgnoredPackets()
{
	QString filename = QDir::homePath() + QString("/.IPFIRE/ignored");
	QFile ignfile(filename);
	
	if (!ignfile.open(QIODevice::WriteOnly | QIODevice::Text))
	{
	  printf("non posso aprire per salvare ignored\n");
		return -1;
	}
	else
	{
		pinfo("saving ignored packets");
		QTextStream out(&ignfile);
		out << "# This is a file generated by the IQFIRE-wall user interface.\n"
		       "# Do not edit it by hand.\n"
			"# The lines starting with a \"#\" are comments that explain the\n"
			"# meaning of each packet below.\n#\n#\n";
		for(int i = 0; i < plist.size(); i++)
		{
			out << "# " << QString("%1: ").arg(i + 1) << plist[i].toReadableString();
			out << plist[i].toString();
		}
		ignfile.close();
	}
	return plist.size();
}


QList<IgnoredPacket> IgnoredPacketsSet::list()
{
	return plist;
}

void IgnoredPacketsSet::add(IgnoredPacket& newp)
{ 
	if(!alreadyPresent(newp))
	{
		plist.push_back(newp); 
		emit ignoredAdded(); 
	}

}

void IgnoredPacketsSet::add(QList<IgnoredPacket> &newlist)
{	
	int i, added = 0;
	for(i = 0; i < newlist.size(); i++)
	{
		if(!alreadyPresent(newlist[i]))
		{
			plist.push_back(newlist[i]);
			added++;
		}
	}
	if(added > 0)
		emit setChanged();
}

bool IgnoredPacketsSet::alreadyPresent( IgnoredPacket &other)
{
	int i;
	
	
	for(i =0; i < plist.size(); i++)
	{
		if(plist[i] == other)
		{
			return true;
		}
	}
	return false;
}

