#!/bin/bash
set -eu

SRCDIR=/usr/src/ipfire-wall

ok()
{
	echo -e  "\n\n\e[1;32m*\e[0m Congratulations!"
	echo -e  "\e[1;32m* \e[0mSuccessfully built and installed ipfire-wall"
}

fail() 
{
	echo -e  "\n\e[1;31mFailed building and installing ipfire-wall \e[1;31m:(\e[0m"
	exit 1
}


self="$(basename "$0")"

action="$1"

if [ "$action" == "configure" ]; then

echo -e "\e[1;32m* Configuring package \""$self"\""

echo -e "\e[1;32m* \e[0m iqfire-wall installation in an ubuntu environment. Welcome!"
echo -e "\e[1;32m* This package will install ipfire-wall/iqfire-wall into your system."
echo -e "\e[1;32m*\e[0m The process might take some time, depending on the speed of your machine."
echo -e "\e[1;32m* \e[0;4mipfire-wall\e[0m and \e[0;4miqfire-wall\e[0m are copyright (C)"
echo -e "\e[1;32m* \e[0mGiacomo Strangolino, \e[0;4mdelleceste@gmail.com\e[0m\n"

(cd $SRCDIR && ./install.sh debian noask && ok ) || fail 

echo -e ""
echo -e "\e[1;32m* \e[0m-------------------------------------------------------------------------------"
echo -e "\e[1;32m* \e[0mWikipedia at http://ipfire-wall.wiki.sourceforge.net/"
echo -e "\e[1;32m* \e[0mDiscussion forums at http://sourceforge.net/forum/?group_id=149121"
echo -e "\e[1;32m* \e[0mProject home page on the developer web site: http://www.giacomos.it/iqfire/index.html"
echo -e "  and http://www.giacomos.it/ipfire/index.html"
echo -e "\e[1;32m* \e[0mubuntu/kubuntu specific installation guide at http://www.giacomos.it/iqfire/ubuntu.html"
echo -e "\e[1;32m* \e[0m-------------------------------------------------------------------------------"
echo -e "\n"

fi
